////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;

namespace OpenNos.GameObject.Packets.ClientPackets
{
    [PacketHeader("gbox")]
    public class GBoxPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte type { get; set; }

        [PacketIndex(1)]
        public int value { get; set; }

        [PacketIndex(2)]
        public int zero { get; set; }

        #endregion
    }
}