////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;

namespace OpenNos.GameObject.Packets.ClientPackets
{
    [PacketHeader("NoS0575")]
    public class LoginPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public int Number { get; set; }

        [PacketIndex(1)]
        public string Name { get; set; }

        [PacketIndex(2)]
        public string Password { get; set; }

        [PacketIndex(3)]
        public string LangKey { get; set; }

        [PacketIndex(4)]
        public string ClientData { get; set; }

        [PacketIndex(5)]
        public string LangData { get; set; }

        [PacketIndex(6)]
        public string ClientVersion { get; set; }

        [PacketIndex(7)]
        public string UID { get; set; }

        [PacketIndex(8)]
        public string Unknown2 { get; set; }

        #endregion
    }
}
