////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;

namespace OpenNos.GameObject
{
    [PacketHeader("pdtclose")]
    public class PdtClosePacket : PacketDefinition
    {
        #region Properties

        #endregion
    }
}