////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$AddSkill", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.GM } )]
    public class AddSkillPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short SkillVNum { get; set; }

        public static string ReturnHelp() => "$AddSkill <VNum>";

        #endregion
    }
}