////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Bank", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.Administrator } )]
    public class BankPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Mode { get; set; }

        [PacketIndex(1)]
        public string Param1 { get; set; }

        [PacketIndex(2)]
        public long Param2 { get; set; }

        public static string ReturnHelp() => "$Bank Help\n$Bank Balance\n$Bank Send <Nickname> <Amount>\n$Bank Deposit <Amount>\n$Bank Withdraw <Amount>";

        #endregion
    }
}