////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$ClassPack", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.GM })]
    public class ClassPackPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short Class { get; set; }

        public static string ReturnHelp() => "$ClassPack <ClassType[1 = Swordsman, 2 = Archer, 3 = Mage]>";

        #endregion
    }
}