////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$FamilyFaction", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.Administrator } )]
    public class FamilyFactionPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string FamilyName { get; set; }

        public static string ReturnHelp() => "$FamilyFaction <Name>";
    }
}