////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Gift", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.CM } )]
    public class GiftPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string CharacterName { get; set; }

        [PacketIndex(1)]
        public short VNum { get; set; }

        [PacketIndex(2)]
        public short Amount { get; set; }

        [PacketIndex(3)]
        public sbyte Rare { get; set; }

        [PacketIndex(4)]
        public byte Upgrade { get; set; }

        [PacketIndex(5)]
        public short Design { get; set; }

        [PacketIndex(6)]
        public short ReceiverLevelMin { get; set; }

        [PacketIndex(7)]
        public short ReceiverLevelMax { get; set; }

        public static string ReturnHelp() => "$Gift <Nickname|*> <VNum> <Amount> <Rare> <Upgrade> <Design> <MinimumLevel> <MaximumLevel>";

        #endregion
    }
}