////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$tp", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.User })]
    public class GoMapPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Mode { get; set; }

        [PacketIndex(1)]
        public string Param1 { get; set; }

        [PacketIndex(2)]
        public long Param2 { get; set; }

        public static string ReturnHelp() => "$GoMap Home / Raid / Lobby";

        #endregion
    }
}