////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$GroupPosition", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.User })]
    public class GroupPositionPacket : PacketDefinition
    {
        public static string ReturnHelp() => "$GroupPosition";
    }
}