////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$DELETE", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.Administrator })]
    public class HomePacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string Item { get; set; }
        public static string ReturnHelp() => "$Home";

        #endregion
    }
}