////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$MapStat", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.Administrator } )]
    public class MapStatisticsPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public short? MapId { get; set; }

        #endregion

        #region Methods

        public static string ReturnHelp() => "$MapStat <?MapId>";

        #endregion
    }
}