////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Miniland", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.GS } )]
    public class MinilandPacket : PacketDefinition
    {
        #region Properties
        [PacketIndex(0)]
        public string CharacterName { get; set; }

        public static string ReturnHelp()
        {
            return "$Miniland <?Nickname>";
        }

        #endregion
    }
}