////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)
using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Music", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.CM })]
    public class MusicPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public string Music { get; set; }

        [PacketIndex(1)]
        public string Maps { get; set; }

        public static string ReturnHelp()
        {
            return "$Music (?)MUSIC (*)nullable";
        }
    }
}