////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$ReloadMI", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.Administrator })]
    public class ReloadMIPacket : PacketDefinition
    {
        #region Properties

        public static string ReturnHelp() => "$ReloadSI";

        #endregion
    }
}