////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$Restart", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.CM } )]
    public class RestartPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int Time { get; set; }

        public static string ReturnHelp() => "$Restart <?Delay>";
    }
}