////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$ChannelInfo", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.GM })]
    public class ServerInfoPacket : PacketDefinition
    {
        [PacketIndex(0)]
        public int? ChannelId { get; set; }

        public static string ReturnHelp() => "$ServerInfo <?ChannelId>";
    }
}