////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{   
    [PacketHeader("$ShowStaff", PassNonParseablePacket = true, Authorities = new AuthorityType[] { AuthorityType.User })]
    public class ShowStaffPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public string gameMasters { get; set; }

        [PacketIndex(2)]
        public string moderators { get; set; }

        [PacketIndex(3)]
        public string preparedString { get; set; }

        public static string ReturnHelp() => "$ShowStaff";

        #endregion
    }
}