////<auto-generated <- Codemaid exclusion for now (PacketIndex Order is important for maintenance)

using OpenNos.Core;
using OpenNos.Domain;

namespace OpenNos.GameObject.CommandPackets
{
    [PacketHeader("$WigColor", PassNonParseablePacket = true, Authorities = new AuthorityType[]{ AuthorityType.GS } )]
    public class WigColorPacket : PacketDefinition
    {
        #region Properties

        [PacketIndex(0)]
        public byte Color { get; set; }

        public static string ReturnHelp() => "$WigColor <Value>";

        #endregion
    }
}