using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenNos.Data
{
    /// <summary>
    /// Represents a DTO class for NosCore.Database.Entities.Title.
    /// NOTE: This class is generated by GenerateDtos.tt
    /// </summary>
[Serializable]
    public class TitleDTO
    {
        public long CharacterId { get; set; }

        public bool Active { get; set; }

        public bool Visible { get; set; }

        public short TitleType { get; set; }

    }
}
